---
# Welcome to Jekyll!

# Website settings
title:
description:
keywords:
baseurl:
url:
img_path:

# author -- index page "about me" section
author:
  name:
  first_name:
  last_name:
  avatar:
  github_username:
  linkedin_id:
  facebook_username:
  twitter_username:
  email:
  cv:
  skill_icon1:
    - name:
    - name:
  skill_icon2:
    - name:
    - name:
  desc:

# comment
# disqus:
#   name:

# analytics
## google analytics
# ga:
#   id:

## google optimize
# go:
#   id:

## growingIO
# gio:
#   id:

## donation
donation: off

## carousels
index_carousel: on
blog_carousel: on

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
