---
# Welcome to Jekyll!

# Website settings
title: Henrick Deschamps
description: "Henrick Deschamps.
  French :fr: Communicating Distributed Systems Ph. D. and engineer &#x1F468&#x200D&#x1F4BB;, I am Interested in real-time distributed systems.
  I am looking for serious technological challenges.
  I would like to contribute to the conception and implementation of complex systems in a team, and to participate in the demonstration of these systems"

keywords:
  hnrck,henrick deschamps,henrick,résumé,Ph.D.,engineer,computer science,
  network,developer,github,gh-pages
baseurl:
url: https://hnrck.github.io
img_path: /static/assets/img/blog

# author -- index page "about me" section
author:
  name: Henrick Deschamps
  first_name: Henrick
  last_name: Deschamps
  avatar: /static/assets/img/avatars/pro1.jpg
  github_username: hnrck
  gitlab_username: hnrck
  linkedin_id: henrick-deschamps
  gsch_user: aTK_XgEAAAAJ
  facebook_username: henrick.deschamps
  twitter_username: dhnrck
  gplus_id: +HenrickDeschamps
  keybase_user: hnrck
  email: contact@hnrck.io
  cv: static/assets/cv_henrick_deschamps.pdf
  skill_icon1:
    - name: fa-cogs
    - name: icon-cplusplus
  skill_icon2:
    - name: fa-linux
    - name: fa-sitemap
  desc: "
    French &#x1F1eb; Communicating Distributed Systems Ph. D. and engineer &#x1F468&#x200D&#x1F4BB;, I am Interested in real-time distributed systems.
    <br>
    I am looking for serious technological challenges.
    I would like to contribute to the conception and implementation of complex systems in a team, and to participate in the demonstration of these systems
    "

# comment
disqus:
  name: hnrck-io

# analytics
## google analytics
ga:
  id: UA-111511980-1

## google optimize
go:
  id: GTM-523R6D6

# TODO(hnrck) complete this action
## growingIO
# gio:
#   id:

## donation
donation: 'off'

## carousels
index_carousel: 'on'
blog_carousel: 'on'

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
